Keymap('n', 'ff', '<CMD>Telescope find_files<CR>', Opts)
Keymap('n', 'fb', '<CMD>Telescope buffers<CR>', Opts)
Keymap('n', 'fg', '<CMD>Telescope live_grep<CR>', Opts)
Keymap('n', 'fh', '<CMD>Telescope howdoi<CR>', Opts)
Keymap('n', 'fp', '<CMD>Telescope projects<CR>', Opts)
Keymap('n', 'fk', '<CMD>Telescope keymaps<CR>', Opts)
