PRequire('nvim-autopairs', function(nvim_autopairs)
    nvim_autopairs.setup()
    PRequire('nvim-autopairs.completion.cmp', function(cmp_autopairs)
        PRequire('cmp', function(cmp)
            cmp.event:on('confirm_done', cmp_autopairs.on_confirm_done({ map_char = { tex = '' } }))
        end)
    end)
end)
